let characters = [
  'Benjamin Linus',
  'Charlie Pace',
  'Christian Shephard',
  'Claire Littleton',
  'Elizabeth "Libby" Smith',
  'Eloise Widmore',
  'Hugo "Hurley" Reyes',
  'Jack Shephard',
  'James "Sawyer" Ford',
  'Jin-Soo Kwon',
  'John Locke',
  'Kate Austen',
  'Miles Straume',
  'Penelope Wilton',
  'Pierre Chang',
  'Richard Alpert',
  'Sayid Jarrah',
  'Sun Kwon',
];
