let episodes = [
  { title: 'Genesis', director: 'David Semel', month: 'September', day: 25, year: 2006 },
  { title: 'Don\'t Look Back', director: 'Allan Arkush', month: 'October', day: 2, year: 2006 },
  { title: 'One Giant Leap', director: 'Greg Beeman', month: 'October', day: 9, year: 2006 },
  { title: 'Collision', director: 'Ernest Dickerson', month: 'October', day: 16, year: 2006 },
  { title: 'Hiros', director: 'Paul Shapiro', month: 'October', day: 23, year: 2006 },
  { title: 'Better Halves', director: 'Greg Beeman', month: 'October', day: 30, year: 2006 },
  { title: 'Nothing to Hide', director: 'Donna Deitch', month: 'November', day: 6, year: 2006 },
  { title: 'Seven Minutes to Midnight', director: 'Paul Edwards', month: 'November', day: 13, year: 2006 },
  { title: 'Homecoming', director: 'Greg Beeman', month: 'November', day: 20, year: 2006 },
  { title: 'Six Months Ago', director: 'Allan Arkush', month: 'November', day: 27, year: 2006 },
  { title: 'Fallout', director: 'John Badham', month: 'December', day: 4, year: 2006 },
  { title: 'Godsend', director: 'Paul Shapiro', month: 'January', day: 22, year: 2007 },
  { title: 'The Fix', director: 'Terrence O\'Hara', month: 'January', day: 29, year: 2007 },
  { title: 'Distractions', director: 'Jeannot Szwarc', month: 'February', day: 5, year: 2007 },
  { title: 'Run!', director: 'Roxann Dawson', month: 'February', day: 12, year: 2007 },
  { title: 'Unexpected', director: 'Greg Beeman', month: 'February', day: 19, year: 2007 },
  { title: 'Company Man', director: 'Allan Arkush', month: 'February', day: 25, year: 2007 },
  { title: 'Parasite', director: 'Kevin Bray', month: 'March', day: 4, year: 2007 },
  { title: '.07%', director: 'Adam Kane', month: 'April', day: 23, year: 2007 },
  { title: 'Five Years Gone', director: 'Paul Edwards', month: 'April', day: 30, year: 2007 },
  { title: 'The Hard Part', director: 'John Badham', month: 'May', day: 7, year: 2007 },
  { title: 'Landslide', director: 'Greg Beeman', month: 'May', day: 14, year: 2007 },
  { title: 'How to Stop an Exploding Man', director: 'Allan Arkush', month: 'May', day: 21, year: 2007 },
];